version: "3.7"

services:
  frontend:
    container_name: trivia
    build: .
    volumes:
      - "./:/trivia"
      - "/trivia/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
