name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn serve
          wait-on: http://localhost:3000
